name: Run Jest Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 0 * * *' # This means every day at 00:00 UTC
  workflow_dispatch: # This enables manual trigger

jobs:
  jest-test-for-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18, 20 ]  # This is how you run on both versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run Jest Test
        run: npx jest test.spec.ts